server:
  port: 8085

config:
  oauth2:
    clientid: test
    clientSecret: test
    privateKey: -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQCjP52DrEsYH4oxrV/POVHzIDsiC7eIxUqcA2kvqJHHWwZUFlVe
      F1keeY+BpzE81T2UxHdvahxZbeq3VMLUe8bxJrrL7ZfjOX92ah1m4KRBHQ/LILYF
      Jc5gfQfkbUjBAQ+1wIXMr3cTkQjSiTAEhbBuIzayvPv7hpavLav8N5Oz/wIDAQAB
      AoGASsDEphjtQhyfMWRMrR14UzZ9HXf0ESMWqR4+ul4ccwdRfIvFh5J1cqkDd8FR
      oKOc0VStxEz4slLM2ipsFNShIerouP7m9Dil8lEaH67C5S5/MDq/aoyi6Nk4L+bZ
      vWqzw5ZSJ9Qps0T6eguQH23B6/kQDnbI7ncxGHPIl8ptbmECQQDtL0u3bP+ZElcx
      ykvPGX8iSwYFCiE5xilbxQlDH8bHQynJcyT3SdLji3XaSf9fGyHdGY0MFk7rt8tW
      jZTbzw9nAkEAsDLV8jssPdizRClD+SPP8M1G9bJcyBJ5MF5MM67jBOIByZuIu+Zr
      mOqT5GZ7GCNZlxFlcNI/iHcyR3k0tniPqQJBANSu93dofx40ywlzvFzeIRmQKrq0
      Ja0X25hV7ANL6ERgHoVtAfXZNgki0jBG8H7I5qnLsqXnDyfh7K0VUil01/sCQQCP
      atF6OW/pZ1mDQZNyVxQKjQwVMPkUYPUDyb180/01HEEYOOEzEHrEHSwD3OaU3zEt
      JZvMGVZdXagvRRkC7V8BAkBbs43Nz0zuShOkNst424Mk9VC//EFb7rlBkBV4nIa1
      8eCPn1Y6VsZF0Wc1Rxm/uJ/SsnV5vyXSbAEtYJ1ElYig
      -----END RSA PRIVATE KEY-----
    publicKey: -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjP52DrEsYH4oxrV/POVHzIDsi
      C7eIxUqcA2kvqJHHWwZUFlVeF1keeY+BpzE81T2UxHdvahxZbeq3VMLUe8bxJrrL
      7ZfjOX92ah1m4KRBHQ/LILYFJc5gfQfkbUjBAQ+1wIXMr3cTkQjSiTAEhbBuIzay
      vPv7hpavLav8N5Oz/wIDAQAB
      -----END PUBLIC KEY-----